"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, GraduationCap, LockKeyhole, Mail, User, UserRoundCheck } from "lucide-react";
import { Brand } from "@/components/shared";

export function TrainerLoginForm() {
  const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch("/api/auth/trainer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const result = await response.json(); if (!response.ok) { setError(result.error); setBusy(false); return; } router.push("/trainer"); router.refresh(); }
  return <LoginShell title="Trainer control room" description="Start lessons, reveal code, launch activities, and guide the room live." icon={<LockKeyhole size={22} />}><form onSubmit={submit} className="space-y-4"><Field label="Username" icon={<User size={17} />} value={username} onChange={setUsername} autoComplete="username" /><Field label="Password" icon={<LockKeyhole size={17} />} value={password} onChange={setPassword} type="password" autoComplete="current-password" />{error && <ErrorText>{error}</ErrorText>}<SubmitButton busy={busy}>Open trainer portal</SubmitButton></form></LoginShell>;
}

export function StudentLoginForm() {
  const router = useRouter(); const [usn, setUsn] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch("/api/auth/student", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ usn, name, email }) }); const result = await response.json(); if (!response.ok) { setError(result.error); setBusy(false); return; } router.push("/student"); router.refresh(); }
  return <LoginShell title="Join the AI mission" description="Enter your classroom details. Your USN keeps your coins and progress connected." icon={<GraduationCap size={22} />}><form onSubmit={submit} className="space-y-4"><Field label="USN" icon={<UserRoundCheck size={17} />} value={usn} onChange={setUsn} placeholder="22CS001" autoComplete="off" /><Field label="Student name" icon={<User size={17} />} value={name} onChange={setName} placeholder="Rahul Kumar" autoComplete="name" /><Field label="Gmail" icon={<Mail size={17} />} value={email} onChange={setEmail} placeholder="rahul@gmail.com" type="email" autoComplete="email" />{error && <ErrorText>{error}</ErrorText>}<SubmitButton busy={busy}>Join live workshop</SubmitButton><p className="text-center text-xs leading-5 text-slate-400">No password needed. Use the same USN to continue your progress.</p></form></LoginShell>;
}

function LoginShell({ title, description, icon, children }: { title: string; description: string; icon: React.ReactNode; children: React.ReactNode }) { return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-slate-50 p-5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_10%,rgba(37,99,235,.13),transparent_28%),radial-gradient(circle_at_85%_80%,rgba(124,58,237,.12),transparent_30%)]" /><div className="relative w-full max-w-md"><div className="mb-7 flex justify-center"><Brand /></div><section className="rounded-3xl border border-white bg-white/90 p-7 shadow-2xl shadow-slate-900/10 backdrop-blur md:p-9"><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-600">{icon}</span><h1 className="mt-6 text-3xl font-black tracking-tight text-slate-950">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{description}</p><div className="mt-7">{children}</div></section><p className="mt-5 text-center text-xs font-semibold text-slate-400">Day 3 · Multi-Agent Orchestration</p></div></main>; }
function Field({ label, icon, value, onChange, type = "text", placeholder, autoComplete }: { label: string; icon: React.ReactNode; value: string; onChange: (value: string) => void; type?: string; placeholder?: string; autoComplete?: string }) { return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">{label}</span><span className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-3.5 focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-100"><span className="text-slate-400">{icon}</span><input required type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} autoComplete={autoComplete} className="h-12 min-w-0 flex-1 bg-transparent text-sm font-semibold text-slate-800 outline-none placeholder:font-normal placeholder:text-slate-300" /></span></label>; }
function SubmitButton({ busy, children }: { busy: boolean; children: React.ReactNode }) { return <button disabled={busy} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-black text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700 disabled:opacity-60">{busy ? "Please wait…" : children}<ArrowRight size={17} /></button>; }
function ErrorText({ children }: { children: React.ReactNode }) { return <p className="rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm font-bold text-rose-700">{children}</p>; }
